# -*- coding: utf-8 -*-
"""prodigy2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jgr6UvoYuX95mzbobsEIHkHtAaDjZFLi
"""

import seaborn as sns

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

# Load the  dataset

df = pd.read_csv("titanic.csv")

#display the first few rows of the dataset

print(df.head())

#basic data cleaning step

# to check for missing values

print(df.isnull().sum())

# Fill missing values in 'Age' column with median age

df['Age'].fillna(tested_df['Age'].median(), inplace=True)

# Fill missing values in 'Embarked' column with most common value

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

#Drop 'Cabin' column due to high number of missing values

df.drop('Cabin', axis=1, inplace=True)

# Create a new feature 'FamilySize' by combining 'SibSp' and 'Parch'
df['FamilySize'] =df['SibSp'] + df['Parch'] + 1

# Create a new feature 'IsAlone' indicating whether the passenger is alone or not
df['IsAlone'] = np.where(df['FamilySize'] == 1, 1, 0)

# Create a new feature 'Title' extracting titles from 'Name'
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Convert categorical variables into numerical ones using one-hot encoding
df = pd.get_dummies(df, columns=['Sex', 'Embarked', 'Title'], drop_first=True)

# exploratory data analysis (EDA):

sns.barplot(x='Sex_male', y='Survived', data=df)
plt.title('Survival Rate by Gender')
plt.show()

sns.barplot(x='Pclass', y='Survived', data=df)
plt.title('Survival Rate by Passenger Class')
plt.show()

sns.histplot(x='Age', hue='Survived', data=df, kde=True)
plt.title('Survival Rate by Age')
plt.show()

sns.barplot(x='FamilySize', y='Survived', data=df)
plt.title('Survival Rate by Family Size')
plt.show()

